language: go
go:
  - 1.14.1
  - tip
matrix:
  allow_failures:
    - go: tip

notifications:
  email:
    recipients: dean.karn@gmail.com
    on_success: change
    on_failure: always

before_install:
  - go install github.com/mattn/goveralls

# Only clone the most recent commit.
git:
  depth: 1

script:
  - go test -v ./...